
node() {
 
    test = new org.foo.Test()
    test.pwd()

    lib = load "./library/Animal.groovy"

    Animal {
        food = 'meat'
    }

    executeWithDocker {
        executeStage("Test") {
            echo "This is only a basic test"
            sh " ls -alt"    
            lib.test()  
        }

        executeStage("Build") {
            echo "This is only a basic test"
            sh " ls -alt"      
        }

        executeStage("Deploy") {
            echo "This is only a basic test"
            sh " ls -alt"   
        }
    }
}